AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure to serve cut-zen.casa

Parameters:
  DomainName:
    Type: String
    Default: cut-zen.casa


Resources:
##########

  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - logs.${Domain}
        - Domain: !Ref DomainName
      AccessControl: LogDeliveryWrite

  DomainBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref DomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref DomainBucket, '/*']]
      Bucket: !Ref DomainBucket

  WWWBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - www.${DomainName}
        - Domain: !Ref DomainName
      AccessControl: BucketOwnerFullControl
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref DomainBucket
