AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainName:
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Join [ '.', [ 'www', !Ref DomainName ] ]
      ValidationMethod: DNS

