AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainName:
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        #- !Ref DomainName
        - !Join [ '.', [ 'www', !Ref DomainName ] ]
      ValidationMethod: DNS

Outputs:
  ACMCertificateArn:
    Value: !Ref Certificate
