AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainName:
    Type: String

Resources:
  DNS:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: !Sub Hosted zone for "${DomainName}"
      Name: !Ref DomainName