AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DomainName:
    Type: String

Resources:
  BucketsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: web/buckets.yml
      Parameters:
        DomainName: !Ref DomainName
# NetworkStack:
#   Type: AWS::CloudFormation::Stack
#   Properties:
#     TemplateURL: network/hosting.yml
#     Parameters:
#       DomainName: !Ref DomainName
