AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DomainName:
    Type: String
  CertificateArn:
    Type: String

Resources:
  BucketsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: web/buckets.yml
      Parameters:
        DomainName: !Ref DomainName
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network/proxy_dns_records.yml
      Parameters:
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
